[2024-05-09 10:53:35,411: INFO: stage_02_data_validation: >>>>>> stage Data Validation stage started <<<<<<]
[2024-05-09 10:53:35,420: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 10:53:35,429: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 10:53:35,436: INFO: common: created directory at: artifacts]
[2024-05-09 10:53:35,436: INFO: common: created directory at: artifacts/data_validation]
[2024-05-09 10:53:35,436: ERROR: stage_02_data_validation: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion']
Traceback (most recent call last):
  File "d:\ml projects\ml pipeline projects\sentiment-analysis-of-flipkart-reviews\src\reviewAnalysis\pipeline\stage_02_data_validation.py", line 23, in <module>
    obj.main()
  File "d:\ml projects\ml pipeline projects\sentiment-analysis-of-flipkart-reviews\src\reviewAnalysis\pipeline\stage_02_data_validation.py", line 14, in main
    data_validation.validate_all_files_exist()
  File "d:\ml projects\ml pipeline projects\sentiment-analysis-of-flipkart-reviews\src\reviewAnalysis\components\data_validation.py", line 32, in validate_all_files_exist
    raise e
  File "d:\ml projects\ml pipeline projects\sentiment-analysis-of-flipkart-reviews\src\reviewAnalysis\components\data_validation.py", line 17, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion'
[2024-05-09 11:03:49,219: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 11:03:49,221: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 11:03:49,228: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 11:03:49,230: INFO: common: created directory at: artifacts]
[2024-05-09 11:03:49,230: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 11:03:49,232: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1Kaym9OHPiizCJ5Gf2LI5qbxvoDWFfFCx/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 11:04:01,842: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1Kaym9OHPiizCJ5Gf2LI5qbxvoDWFfFCx/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 11:04:03,059: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-09 11:04:03,063: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-05-09 11:04:03,067: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 11:04:03,071: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 11:04:03,071: INFO: common: created directory at: artifacts]
[2024-05-09 11:04:03,074: INFO: common: created directory at: artifacts/data_validation]
[2024-05-09 11:04:03,083: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-05-09 11:04:03,083: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-05-09 11:04:03,087: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 11:04:03,090: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 11:04:03,090: INFO: common: created directory at: artifacts]
[2024-05-09 11:04:03,090: INFO: common: created directory at: artifacts/data_transformation]
[2024-05-09 11:04:12,487: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-05-09 11:04:12,487: INFO: main: *******************]
[2024-05-09 11:04:12,487: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-05-09 11:04:12,495: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 11:04:12,502: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 11:04:12,504: INFO: common: created directory at: artifacts]
[2024-05-09 11:04:12,504: INFO: common: created directory at: artifacts/model_trainer]
[2024-05-09 14:23:46,222: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 14:23:46,222: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:23:46,231: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:23:46,231: INFO: common: created directory at: artifacts]
[2024-05-09 14:23:46,232: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 14:23:46,232: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 14:23:48,954: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 14:23:48,972: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-09 14:40:26,939: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 14:40:26,953: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:40:26,960: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:40:26,960: INFO: common: created directory at: artifacts]
[2024-05-09 14:40:26,962: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 14:40:26,962: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 14:40:29,457: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 14:40:29,475: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-09 14:40:29,475: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-05-09 14:40:29,477: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:40:29,477: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:40:29,477: INFO: common: created directory at: artifacts]
[2024-05-09 14:40:29,477: INFO: common: created directory at: artifacts/data_validation]
[2024-05-09 14:40:29,483: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-05-09 14:40:29,484: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-05-09 14:40:29,487: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:40:29,488: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:40:29,489: INFO: common: created directory at: artifacts]
[2024-05-09 14:40:29,489: INFO: common: created directory at: artifacts/data_transformation]
[2024-05-09 14:40:29,529: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-05-09 14:46:04,669: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 14:46:04,673: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:46:04,676: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:46:04,676: INFO: common: created directory at: artifacts]
[2024-05-09 14:46:04,677: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 14:46:04,677: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 14:46:06,926: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 14:46:06,941: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-09 14:46:06,942: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-05-09 14:46:06,943: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:46:06,947: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:46:06,947: INFO: common: created directory at: artifacts]
[2024-05-09 14:46:06,948: INFO: common: created directory at: artifacts/data_validation]
[2024-05-09 14:46:06,949: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-05-09 14:46:06,950: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-05-09 14:46:06,952: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:46:06,955: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:46:06,955: INFO: common: created directory at: artifacts]
[2024-05-09 14:46:06,956: INFO: common: created directory at: artifacts/data_transformation]
[2024-05-09 14:46:06,991: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-05-09 14:46:06,992: INFO: main: *******************]
[2024-05-09 14:46:06,993: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-05-09 14:46:06,995: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:46:06,995: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:46:06,998: INFO: common: created directory at: artifacts]
[2024-05-09 14:46:06,999: INFO: common: created directory at: artifacts/model_trainer]
[2024-05-09 14:46:07,970: ERROR: main: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 1), output.shape=(None, 5)]
Traceback (most recent call last):
  File "D:\ML projects\ML Pipeline Projects\Sentiment-Analysis-of-Flipkart-Reviews\main.py", line 50, in <module>
    model_trainer.main()
  File "d:\ml projects\ml pipeline projects\sentiment-analysis-of-flipkart-reviews\src\reviewAnalysis\pipeline\stage_04_model_trainer.py", line 14, in main
    model_trainer_config.train()
  File "d:\ml projects\ml pipeline projects\sentiment-analysis-of-flipkart-reviews\src\reviewAnalysis\components\model_trainer.py", line 61, in train
    model.fit(sequences_matrix,y_train,batch_size=self.config.batch_size,epochs = self.config.epochs,validation_split=self.config.validation_split)
  File "C:\Users\subhayu\anaconda3\envs\review\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\subhayu\anaconda3\envs\review\Lib\site-packages\keras\src\backend\tensorflow\nn.py", line 554, in categorical_crossentropy
    raise ValueError(
ValueError: Arguments `target` and `output` must have the same shape. Received: target.shape=(None, 1), output.shape=(None, 5)
[2024-05-09 14:47:53,095: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 14:47:53,099: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:47:53,099: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:47:53,099: INFO: common: created directory at: artifacts]
[2024-05-09 14:47:53,099: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 14:47:53,099: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 14:47:55,143: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 14:47:55,158: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-09 14:47:55,159: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-05-09 14:47:55,161: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:47:55,163: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:47:55,163: INFO: common: created directory at: artifacts]
[2024-05-09 14:47:55,164: INFO: common: created directory at: artifacts/data_validation]
[2024-05-09 14:47:55,164: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-05-09 14:47:55,165: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-05-09 14:47:55,167: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:47:55,170: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:47:55,170: INFO: common: created directory at: artifacts]
[2024-05-09 14:47:55,171: INFO: common: created directory at: artifacts/data_transformation]
[2024-05-09 14:47:55,205: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-05-09 14:47:55,206: INFO: main: *******************]
[2024-05-09 14:47:55,206: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-05-09 14:47:55,210: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:47:55,210: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:47:55,210: INFO: common: created directory at: artifacts]
[2024-05-09 14:47:55,210: INFO: common: created directory at: artifacts/model_trainer]
[2024-05-09 14:47:55,337: ERROR: main: name 'pad_sequences' is not defined]
Traceback (most recent call last):
  File "D:\ML projects\ML Pipeline Projects\Sentiment-Analysis-of-Flipkart-Reviews\main.py", line 50, in <module>
    model_trainer.main()
  File "d:\ml projects\ml pipeline projects\sentiment-analysis-of-flipkart-reviews\src\reviewAnalysis\pipeline\stage_04_model_trainer.py", line 14, in main
    model_trainer_config.train()
  File "d:\ml projects\ml pipeline projects\sentiment-analysis-of-flipkart-reviews\src\reviewAnalysis\components\model_trainer.py", line 44, in train
    sequences_matrix_train = pad_sequences(sequences_train, maxlen=max_len)
                             ^^^^^^^^^^^^^
NameError: name 'pad_sequences' is not defined
[2024-05-09 14:48:40,614: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 14:48:40,616: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:48:40,619: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:48:40,620: INFO: common: created directory at: artifacts]
[2024-05-09 14:48:40,620: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 14:48:40,621: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 14:48:42,693: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 14:48:42,710: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-09 14:48:42,710: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-05-09 14:48:42,712: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:48:42,715: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:48:42,715: INFO: common: created directory at: artifacts]
[2024-05-09 14:48:42,716: INFO: common: created directory at: artifacts/data_validation]
[2024-05-09 14:48:42,717: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-05-09 14:48:42,718: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-05-09 14:48:42,721: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:48:42,723: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:48:42,724: INFO: common: created directory at: artifacts]
[2024-05-09 14:48:42,725: INFO: common: created directory at: artifacts/data_transformation]
[2024-05-09 14:48:42,758: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-05-09 14:48:42,758: INFO: main: *******************]
[2024-05-09 14:48:42,758: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-05-09 14:48:42,762: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:48:42,766: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:48:42,766: INFO: common: created directory at: artifacts]
[2024-05-09 14:48:42,767: INFO: common: created directory at: artifacts/model_trainer]
[2024-05-09 14:48:52,655: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-09 14:48:52,767: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-05-09 14:57:53,592: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 14:57:53,598: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:57:53,600: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:57:53,600: INFO: common: created directory at: artifacts]
[2024-05-09 14:57:53,600: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 14:57:53,600: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 14:57:55,773: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 14:57:55,791: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-09 14:57:55,792: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-05-09 14:57:55,793: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:57:55,796: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:57:55,797: INFO: common: created directory at: artifacts]
[2024-05-09 14:57:55,797: INFO: common: created directory at: artifacts/data_validation]
[2024-05-09 14:57:55,798: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-05-09 14:57:55,800: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-05-09 14:57:55,802: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:57:55,804: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:57:55,805: INFO: common: created directory at: artifacts]
[2024-05-09 14:57:55,805: INFO: common: created directory at: artifacts/data_transformation]
[2024-05-09 14:57:55,840: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-05-09 14:57:55,846: INFO: main: *******************]
[2024-05-09 14:57:55,846: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-05-09 14:57:55,849: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 14:57:55,850: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 14:57:55,852: INFO: common: created directory at: artifacts]
[2024-05-09 14:57:55,853: INFO: common: created directory at: artifacts/model_trainer]
[2024-05-09 14:58:06,298: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-09 14:58:06,383: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-05-09 18:45:01,728: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 18:45:01,745: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 18:45:01,756: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 18:45:01,756: INFO: common: created directory at: artifacts]
[2024-05-09 18:45:01,758: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 18:45:01,758: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 18:45:05,398: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 18:45:05,420: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-09 18:45:05,420: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-05-09 18:45:05,426: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 18:45:05,428: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 18:45:05,429: INFO: common: created directory at: artifacts]
[2024-05-09 18:45:05,429: INFO: common: created directory at: artifacts/data_validation]
[2024-05-09 18:45:05,431: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-05-09 18:45:05,431: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-05-09 18:45:05,434: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 18:45:05,434: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 18:45:05,439: INFO: common: created directory at: artifacts]
[2024-05-09 18:45:05,439: INFO: common: created directory at: artifacts/data_transformation]
[2024-05-09 18:45:05,519: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-05-09 18:45:05,519: INFO: main: *******************]
[2024-05-09 18:45:05,519: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-05-09 18:45:05,525: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 18:45:05,529: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 18:45:05,529: INFO: common: created directory at: artifacts]
[2024-05-09 18:45:05,529: INFO: common: created directory at: artifacts/model_trainer]
[2024-05-09 18:45:19,509: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-09 18:45:19,593: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-05-09 18:49:27,628: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 18:49:27,644: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 18:49:27,646: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 18:49:27,646: INFO: common: created directory at: artifacts]
[2024-05-09 18:49:27,649: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 18:49:27,649: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 18:49:30,627: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 18:49:30,652: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-09 18:52:19,597: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 18:52:19,613: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 18:52:19,613: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 18:52:19,613: INFO: common: created directory at: artifacts]
[2024-05-09 18:52:19,618: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 18:52:19,619: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 18:52:22,277: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 18:52:22,315: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-09 18:54:34,031: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 18:54:34,041: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 18:54:34,048: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 18:54:34,048: INFO: common: created directory at: artifacts]
[2024-05-09 18:54:34,048: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 18:54:34,050: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 18:54:37,803: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 18:54:37,828: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-09 18:54:37,828: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-05-09 18:54:37,830: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 18:54:37,836: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 18:54:37,836: INFO: common: created directory at: artifacts]
[2024-05-09 18:54:37,836: INFO: common: created directory at: artifacts/data_validation]
[2024-05-09 18:54:37,840: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-05-09 18:54:37,842: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-05-09 18:54:37,846: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 18:54:37,847: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 18:54:37,847: INFO: common: created directory at: artifacts]
[2024-05-09 18:54:37,847: INFO: common: created directory at: artifacts/data_transformation]
[2024-05-09 18:54:37,911: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-05-09 18:54:37,912: INFO: main: *******************]
[2024-05-09 18:54:37,912: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-05-09 18:54:37,916: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 18:54:37,920: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 18:54:37,920: INFO: common: created directory at: artifacts]
[2024-05-09 18:54:37,922: INFO: common: created directory at: artifacts/model_trainer]
[2024-05-09 18:54:49,227: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-09 18:54:49,324: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-09 18:54:49,382: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-05-09 18:56:32,826: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 18:56:32,832: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 18:56:32,832: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 18:56:32,834: INFO: common: created directory at: artifacts]
[2024-05-09 18:56:32,836: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 18:56:32,837: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 18:56:35,968: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 18:56:35,996: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-09 18:59:07,188: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 18:59:07,191: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 18:59:07,195: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 18:59:07,197: INFO: common: created directory at: artifacts]
[2024-05-09 18:59:07,197: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 18:59:07,197: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 18:59:09,912: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 18:59:09,947: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-09 18:59:10,809: INFO: stage_02_data_validation: >>>>>> stage Data Validation stage started <<<<<<]
[2024-05-09 18:59:10,814: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 18:59:10,814: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 18:59:10,822: INFO: common: created directory at: artifacts]
[2024-05-09 18:59:10,822: INFO: common: created directory at: artifacts/data_validation]
[2024-05-09 18:59:10,830: INFO: stage_02_data_validation: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-05-09 18:59:16,118: INFO: stage_03_data_transformation: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-05-09 18:59:16,119: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 18:59:16,123: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 18:59:16,123: INFO: common: created directory at: artifacts]
[2024-05-09 18:59:16,125: INFO: common: created directory at: artifacts/data_transformation]
[2024-05-09 18:59:16,172: INFO: stage_03_data_transformation: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-05-09 18:59:25,144: INFO: stage_04_model_trainer: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-05-09 18:59:25,144: ERROR: stage_04_model_trainer: ModelTrainer.__init__() missing 1 required positional argument: 'config']
Traceback (most recent call last):
  File "D:\ML projects\ML Pipeline Projects\Sentiment-Analysis-of-Flipkart-Reviews\src\reviewAnalysis\pipeline\stage_04_model_trainer.py", line 22, in <module>
    obj = ModelTrainer()
          ^^^^^^^^^^^^^^
TypeError: ModelTrainer.__init__() missing 1 required positional argument: 'config'
[2024-05-09 19:00:57,341: INFO: stage_04_model_trainer: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-05-09 19:00:57,343: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:00:57,346: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:00:57,349: INFO: common: created directory at: artifacts]
[2024-05-09 19:00:57,349: INFO: common: created directory at: artifacts/model_trainer]
[2024-05-09 19:01:10,042: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-09 19:01:10,129: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-09 19:01:10,203: INFO: stage_04_model_trainer: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-05-09 19:03:55,098: INFO: stage_04_model_trainer: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-05-09 19:03:55,103: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:03:55,107: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:03:55,108: INFO: common: created directory at: artifacts]
[2024-05-09 19:03:55,109: INFO: common: created directory at: artifacts/model_trainer]
[2024-05-09 19:04:06,411: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-09 19:04:06,484: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-09 19:04:06,560: INFO: stage_04_model_trainer: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-05-09 19:08:03,613: INFO: stage_04_model_trainer: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-05-09 19:08:03,621: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:08:03,625: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:08:03,627: INFO: common: created directory at: artifacts]
[2024-05-09 19:08:03,627: INFO: common: created directory at: artifacts/model_trainer]
[2024-05-09 19:08:15,384: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-09 19:08:15,462: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-09 19:08:15,524: INFO: stage_04_model_trainer: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-05-09 19:48:55,524: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 19:48:55,524: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:48:55,524: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:48:55,524: INFO: common: created directory at: artifacts]
[2024-05-09 19:48:55,536: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 19:48:55,536: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 19:48:58,359: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 19:48:58,378: ERROR: main: [Errno 13] Permission denied: 'artifacts\\data_ingestion\\flipkart.csv']
Traceback (most recent call last):
  File "D:\ML projects\ML Pipeline Projects\Sentiment-Analysis-of-Flipkart-Reviews\main.py", line 13, in <module>
    data_ingestion.main()
  File "d:\ml projects\ml pipeline projects\sentiment-analysis-of-flipkart-reviews\src\reviewAnalysis\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.extract_zip_file()
  File "d:\ml projects\ml pipeline projects\sentiment-analysis-of-flipkart-reviews\src\reviewAnalysis\components\data_ingestion.py", line 47, in extract_zip_file
    zip_ref.extractall(unzip_path)
  File "C:\Users\subhayu\anaconda3\envs\review\Lib\zipfile\__init__.py", line 1744, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\subhayu\anaconda3\envs\review\Lib\zipfile\__init__.py", line 1801, in _extract_member
    open(targetpath, "wb") as target:
    ^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'artifacts\\data_ingestion\\flipkart.csv'
[2024-05-09 19:50:52,042: INFO: stage_05_model_evaluation: *******************]
[2024-05-09 19:50:52,042: INFO: stage_05_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-09 19:50:52,044: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:50:52,050: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:50:52,050: INFO: common: created directory at: artifacts]
[2024-05-09 19:50:52,052: ERROR: stage_05_model_evaluation: [Errno 2] Unable to synchronously open file (unable to open file: name = 'artifacts/training/model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)]
Traceback (most recent call last):
  File "D:\ML projects\ML Pipeline Projects\Sentiment-Analysis-of-Flipkart-Reviews\src\reviewAnalysis\pipeline\stage_05_model_evaluation.py", line 27, in <module>
    obj.main()
  File "D:\ML projects\ML Pipeline Projects\Sentiment-Analysis-of-Flipkart-Reviews\src\reviewAnalysis\pipeline\stage_05_model_evaluation.py", line 18, in main
    evaluation.evaluation()
  File "d:\ml projects\ml pipeline projects\sentiment-analysis-of-flipkart-reviews\src\reviewAnalysis\components\model_evaluation.py", line 38, in evaluation
    self.model = self.load_model(self.config.path_of_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ml projects\ml pipeline projects\sentiment-analysis-of-flipkart-reviews\src\reviewAnalysis\components\model_evaluation.py", line 35, in load_model
    return tf.keras.models.load_model(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\subhayu\anaconda3\envs\review\Lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\subhayu\anaconda3\envs\review\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\subhayu\anaconda3\envs\review\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\subhayu\anaconda3\envs\review\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'artifacts/training/model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-05-09 19:52:13,655: INFO: stage_05_model_evaluation: *******************]
[2024-05-09 19:52:13,655: INFO: stage_05_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-09 19:52:13,657: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:52:13,662: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:52:13,664: INFO: common: created directory at: artifacts]
[2024-05-09 19:52:13,665: ERROR: stage_05_model_evaluation: [Errno 22] Unable to synchronously open file (unable to open file: name = 'srceviewAnalysis\models\model.h5', errno = 22, error message = 'Invalid argument', flags = 0, o_flags = 0)]
Traceback (most recent call last):
  File "D:\ML projects\ML Pipeline Projects\Sentiment-Analysis-of-Flipkart-Reviews\src\reviewAnalysis\pipeline\stage_05_model_evaluation.py", line 27, in <module>
    obj.main()
  File "D:\ML projects\ML Pipeline Projects\Sentiment-Analysis-of-Flipkart-Reviews\src\reviewAnalysis\pipeline\stage_05_model_evaluation.py", line 18, in main
    evaluation.evaluation()
  File "d:\ml projects\ml pipeline projects\sentiment-analysis-of-flipkart-reviews\src\reviewAnalysis\components\model_evaluation.py", line 38, in evaluation
    self.model = self.load_model(self.config.path_of_model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\ml projects\ml pipeline projects\sentiment-analysis-of-flipkart-reviews\src\reviewAnalysis\components\model_evaluation.py", line 35, in load_model
    return tf.keras.models.load_model(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\subhayu\anaconda3\envs\review\Lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\subhayu\anaconda3\envs\review\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\subhayu\anaconda3\envs\review\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\subhayu\anaconda3\envs\review\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
OSError: [Errno 22] Unable to synchronously open file (unable to open file: name = 'srceviewAnalysis\models\model.h5', errno = 22, error message = 'Invalid argument', flags = 0, o_flags = 0)
[2024-05-09 19:52:40,793: INFO: stage_05_model_evaluation: *******************]
[2024-05-09 19:52:40,793: INFO: stage_05_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-09 19:52:40,798: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:52:40,801: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:52:40,802: INFO: common: created directory at: artifacts]
[2024-05-09 19:52:41,014: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-09 19:54:16,947: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 19:54:16,949: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:54:16,954: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:54:16,955: INFO: common: created directory at: artifacts]
[2024-05-09 19:54:16,955: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 19:54:16,958: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 19:54:20,280: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 19:54:20,306: ERROR: main: [Errno 13] Permission denied: 'artifacts\\data_ingestion\\flipkart.csv']
Traceback (most recent call last):
  File "D:\ML projects\ML Pipeline Projects\Sentiment-Analysis-of-Flipkart-Reviews\main.py", line 13, in <module>
    data_ingestion.main()
  File "d:\ml projects\ml pipeline projects\sentiment-analysis-of-flipkart-reviews\src\reviewAnalysis\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.extract_zip_file()
  File "d:\ml projects\ml pipeline projects\sentiment-analysis-of-flipkart-reviews\src\reviewAnalysis\components\data_ingestion.py", line 47, in extract_zip_file
    zip_ref.extractall(unzip_path)
  File "C:\Users\subhayu\anaconda3\envs\review\Lib\zipfile\__init__.py", line 1744, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\subhayu\anaconda3\envs\review\Lib\zipfile\__init__.py", line 1801, in _extract_member
    open(targetpath, "wb") as target:
    ^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'artifacts\\data_ingestion\\flipkart.csv'
[2024-05-09 19:56:18,553: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 19:56:18,560: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:56:18,564: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:56:18,565: INFO: common: created directory at: artifacts]
[2024-05-09 19:56:18,565: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 19:56:18,568: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 19:56:21,242: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 19:56:21,271: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-09 19:56:21,271: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-05-09 19:56:21,276: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:56:21,279: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:56:21,279: INFO: common: created directory at: artifacts]
[2024-05-09 19:56:21,284: INFO: common: created directory at: artifacts/data_validation]
[2024-05-09 19:56:21,285: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-05-09 19:56:21,285: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-05-09 19:56:21,289: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:56:21,289: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:56:21,289: INFO: common: created directory at: artifacts]
[2024-05-09 19:56:21,298: INFO: common: created directory at: artifacts/data_transformation]
[2024-05-09 19:56:21,373: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-05-09 19:56:21,374: INFO: main: *******************]
[2024-05-09 19:56:21,374: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-05-09 19:56:21,376: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:56:21,381: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:56:21,381: INFO: common: created directory at: artifacts]
[2024-05-09 19:56:21,384: INFO: common: created directory at: artifacts/model_trainer]
[2024-05-09 19:56:35,318: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-09 19:56:35,426: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-09 19:56:35,496: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-05-09 19:57:15,715: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-09 19:57:15,718: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:57:15,723: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:57:15,724: INFO: common: created directory at: artifacts]
[2024-05-09 19:57:15,724: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-09 19:57:15,726: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 19:57:18,501: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1fcbd8ZTQhpmxGSjuml_iz9NTPUkZkAaf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-09 19:57:18,543: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-09 19:57:18,543: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2024-05-09 19:57:18,549: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:57:18,553: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:57:18,553: INFO: common: created directory at: artifacts]
[2024-05-09 19:57:18,553: INFO: common: created directory at: artifacts/data_validation]
[2024-05-09 19:57:18,553: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2024-05-09 19:57:18,559: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-05-09 19:57:18,562: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:57:18,567: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:57:18,569: INFO: common: created directory at: artifacts]
[2024-05-09 19:57:18,569: INFO: common: created directory at: artifacts/data_transformation]
[2024-05-09 19:57:18,652: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-05-09 19:57:18,653: INFO: main: *******************]
[2024-05-09 19:57:18,653: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-05-09 19:57:18,653: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:57:18,661: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:57:18,663: INFO: common: created directory at: artifacts]
[2024-05-09 19:57:18,663: INFO: common: created directory at: artifacts/model_trainer]
[2024-05-09 19:57:32,573: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-09 19:57:32,660: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-09 19:57:32,741: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2024-05-09 19:57:32,741: INFO: main: *******************]
[2024-05-09 19:57:32,741: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-09 19:57:32,745: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-09 19:57:32,747: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-09 19:57:32,747: INFO: common: created directory at: artifacts]
[2024-05-09 19:57:32,853: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
